'use strict';
const $=id=>document.getElementById(id),T=THREE;
let renderer;
try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:false,alpha:false});}catch(e){const t=$('title');t.replaceChildren();const h=document.createElement('h2');h.textContent='3D表示を開始できませんでした';const p=document.createElement('p');p.textContent='WebGL対応のブラウザで開いてください。';t.append(h,p);throw e;}
renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;
const scene=new T.Scene();scene.background=new T.Color('#9dcbd2');scene.fog=new T.Fog('#9dcbd2',45,105);
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,180);const ambient=new T.HemisphereLight(0xfff0d1,0x467c81,.8);scene.add(ambient);
const sun=new T.DirectionalLight(0xffe6b5,1.0);sun.position.set(-18,35,18);sun.castShadow=false;scene.add(sun);
const matCache={};function mat(c){return matCache[c]||(matCache[c]=new T.MeshStandardMaterial({color:c,roughness:.87,flatShading:true}));}
function mesh(geo,c,x=0,y=0,z=0,parent=scene){const m=new T.Mesh(geo,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const box=(w,h,d,c,x,y,z,p)=>mesh(new T.BoxGeometry(w,h,d),c,x,y,z,p);
const cone=(r,h,c,x,y,z,p,n=6)=>mesh(new T.ConeGeometry(r,h,n),c,x,y,z,p);
const ball=(r,c,x,y,z,p)=>mesh(new T.IcosahedronGeometry(r,1),c,x,y,z,p);
function group(x,z){let g=new T.Group();g.position.set(x,0,z);scene.add(g);return g;}
let seed=824;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const water=mesh(new T.PlaneGeometry(500,500),0x64adb8,0,-.8,0);water.rotation.x=-Math.PI/2;water.receiveShadow=false;
mesh(new T.CylinderGeometry(35,32,2.7,64),0xb5b990,0,-1.5,0);mesh(new T.CylinderGeometry(33.9,35,.65,64),0x83aa66,0,-.18,0);
function path(x,z,w,d,rot=0){let m=box(w,.035,d,0xc9bf8c,x,.16,z);m.rotation.y=rot;}
path(0,4,3,44);path(-9,7,20,2.8,.3);path(10,-5,22,2.8,-.52);path(-8,-10,21,2.5,.8);
const obstacles=[];function tree(x,z,s=1){let g=group(x,z);box(.35,1.8,.35,0x80664c,0,.9,0,g);cone(1.7,3.2,0x3d7864,0,2.8,0,g);cone(1.25,2.7,0x53886a,0,4,0,g);g.scale.setScalar(s);obstacles.push({x,z,r:1*s});}
for(let i=0;i<100;i++){let a=rand()*Math.PI*2,r=12+rand()*20,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)<4||Math.hypot(x+13,z-10)<7||Math.hypot(x,z+23)<8)continue;tree(x,z,.65+rand()*.55);}
for(let i=0;i<180;i++){let x=(rand()-.5)*64,z=(rand()-.5)*64;if(Math.hypot(x,z)>32)continue;let g=cone(.12,.35,rand()>.6?0xf1da94:0x9db878,x,.2,z);g.rotation.z=.2;}
for(let i=0;i<25;i++){let a=rand()*6.28,r=31+rand()*3;let m=ball(.7+rand(),0x9eac9a,Math.cos(a)*r,.1,Math.sin(a)*r);m.scale.y=.65;}
function house(x,z,rot=0){let g=group(x,z);g.rotation.y=rot;box(3.4,2.6,3,0xefe0b4,0,1.3,0,g);let roof=cone(2.8,1.9,0xb9694c,0,3.5,0,g,4);roof.rotation.y=Math.PI/4;box(.75,1.5,.1,0x5b6661,0,.75,1.53,g);box(.65,.7,.1,0x89bac0,-1,1.6,1.54,g);box(.45,1.1,.45,0xc9ba9c,1,3.5,-.6,g);obstacles.push({x,z,r:2.4});}
house(-15,12,.3);house(-20,7,.7);house(-12,5,-.4);
const well=group(-12,12);mesh(new T.CylinderGeometry(.95,1,1,10),0xd6cbb0,0,.5,0,well);mesh(new T.CylinderGeometry(.7,.7,.05,12),0x5cbbc5,0,1.02,0,well);
function human(x,z,color=0x426db2){let g=group(x,z);box(.68,.95,.45,color,0,1.1,0,g);ball(.4,0xf0c59b,0,1.88,0,g);let hair=ball(.41,0x594837,0,2.03,-.06,g);hair.scale.y=.6;const legs=[box(.24,.6,.27,0x354950,-.19,.35,0,g),box(.24,.6,.27,0x354950,.19,.35,0,g)];box(.22,.74,.24,0xf0c59b,-.48,1.1,0,g);box(.22,.74,.24,0xf0c59b,.48,1.1,0,g);return {g,legs};}
const elder=human(-10,11,0xe4be6d);cone(.52,.8,0xf2e1b8,0,2.36,0,elder.g);const hero=human(0,15);let cape=box(.75,1,.08,0xa54343,0,1.06,-.29,hero.g);cape.rotation.x=-.15;box(.1,1.05,.14,0xe6e9dd,.63,1.02,.1,hero.g);box(.4,.12,.2,0xe7c987,.63,.64,.1,hero.g);let shield=mesh(new T.CylinderGeometry(.4,.4,.12,6),0xcaa963,-.58,1,.15,hero.g);shield.rotation.x=Math.PI/2;
const shrinePositions=[[-21,-7],[18,4],[6,-17]];const shrines=shrinePositions.map(([x,z],i)=>{let g=group(x,z);box(2.6,.35,2.6,0xccceb4,0,.2,0,g);for(let s of [-1,1]){box(.35,2.8,.35,0xc6d0bd,s,1.55,0,g);}box(2.7,.4,.65,0xe1ddc5,0,3,0,g);let gem=mesh(new T.OctahedronGeometry(.58),0x8af2df,0,1.65,0,g);const light=new T.PointLight(0x8fffe1,1,5);light.position.y=2;g.add(light);return {g,gem,x,z,i};});
const castle=group(0,-25);box(8,4,4,0x829394,0,2,0,castle);for(let x of [-4,4]){mesh(new T.CylinderGeometry(1.4,1.55,6,8),0xa3aaa0,x,3,0,castle);cone(1.9,2.5,0x475968,x,7.2,0,castle);}box(2,2.7,.1,0x314a50,0,1.35,2.06,castle);for(let x=-3;x<=3;x+=1.5)box(.7,.7,4,0xa3aaa0,x,4.3,0,castle);obstacles.push({x:0,z:-25,r:4.6});
function slime(x,z,c=0x50b9d0){let g=group(x,z);let b=ball(.95,c,0,.65,0,g);b.scale.set(1,.72,1);cone(.48,.8,c,0,1.3,0,g);for(let s of [-1,1]){ball(.14,0xffffff,s*.28,.83,.77,g);ball(.065,0x17364b,s*.28,.83,.895,g);}let mouth=box(.28,.06,.05,0xa95456,0,.58,.9,g);return g;}
function dragon(x,z){let g=group(x,z);ball(1.4,0x6c788e,0,1.6,0,g);ball(.9,0x929896,0,2.7,.65,g);box(1.1,.5,1.15,0xa7a89b,0,2.42,1.2,g);for(let s of [-1,1]){cone(.22,.9,0xf0d5a0,s*.6,3.6,.45,g);ball(.15,0xffcc69,s*.57,2.86,1.28,g);box(.5,.65,.9,0x69798c,s*.8,.4,.6,g);let wing=mesh(new T.ConeGeometry(1.8,2.7,3),0x967784,s*1.8,2.1,-.2,g);wing.rotation.z=s*1;wing.scale.z=.16;}let tail=cone(.6,2.6,0x69798c,0,.9,-1.7,g);tail.rotation.x=-1;return g;}
const enemyDefs=[[-5,6,0],[7,8,0],[-8,-3,0],[16,0,1],[-19,-9,1],[8,-13,1]];
const enemies=enemyDefs.map(([x,z,type],i)=>({x,z,type,id:i,g:slime(x,z,type?0xbca7d4:0x51b6d1),dead:false,cool:0}));const boss={x:0,z:-19,type:2,id:6,g:dragon(0,-19),dead:false,cool:0};enemies.push(boss);
const clouds=[];for(let i=0;i<12;i++){let g=group((rand()-.5)*110,(rand()-.5)*110);g.position.y=16+rand()*6;for(let j=0;j<3;j++){let b=ball(2.5,0xe7efe2,j*2,0,0,g);b.scale.set(1.4,.45,1);}clouds.push(g);}
let state='title',p={x:0,z:15,hp:60,mp:16,level:1,xp:0,gold:0,herbs:4,crystals:[],won:false},yaw=.1,time=0,last=0,steps=0,battle=null,busy=false,dialogDone=null,mute=true,audio=null,toastTimer,paused=false,bgmNode=null;
const key={},joy={x:0,y:0};const saveKey='dq3d-island-v1';const muteKey='tg.244.mute';const maxHP=()=>60+(p.level-1)*16,maxMP=()=>16+(p.level-1)*4;
try{mute=localStorage.getItem(muteKey)!=='0';}catch{}
function unlockAudio(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const buf=audio.createBuffer(1,1,22050);const src=audio.createBufferSource();src.buffer=buf;src.connect(audio.destination);src.start(0);startBgm();}catch{}}
function startBgm(){if(!audio||mute||bgmNode)return;try{const buf=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.sin(2*Math.PI*196*i/audio.sampleRate)*0.025+Math.sin(2*Math.PI*247*i/audio.sampleRate)*0.012;const src=audio.createBufferSource();const g=audio.createGain();g.gain.value=0.22;src.buffer=buf;src.loop=true;src.connect(g);g.connect(audio.destination);src.start();bgmNode=src;}catch{}}
function stopBgm(){if(bgmNode){try{bgmNode.stop();}catch{}bgmNode=null;}}
function setMute(next){mute=next;try{localStorage.setItem(muteKey,mute?'1':'0');}catch{}$('sound').textContent='音 '+(mute?'OFF':'ON');$('sound').setAttribute('aria-pressed',mute?'true':'false');if($('btnMuteDlg'))$('btnMuteDlg').textContent=mute?'音: オフ':'音: オン';if(mute)stopBgm();else{unlockAudio();startBgm();}}
function sound(notes=[440],duration=.12){if(mute)return;try{unlockAudio();notes.forEach((n,i)=>{let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*duration;o.type='triangle';o.frequency.value=n;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.07,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+duration);});}catch{}}
function bindTap(el,handler){if(!el)return;const fire=e=>{e.preventDefault();try{el.setPointerCapture(e.pointerId);}catch{}el.classList.add('is-pressed');if(navigator.vibrate)navigator.vibrate(15);handler(e);};const release=()=>el.classList.remove('is-pressed');el.addEventListener('pointerdown',fire);el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('pointerleave',release);}
function syncMuteUi(){$('sound').textContent='音 '+(mute?'OFF':'ON');$('sound').setAttribute('aria-pressed',mute?'true':'false');if($('btnMuteDlg'))$('btnMuteDlg').textContent=mute?'音: オフ':'音: オン';}
syncMuteUi();
function setPaused(on){if(state==='title'||state==='ending')return;paused=on;if(on){try{$('pauseDlg').showModal();}catch{}$('pauseDlg').dataset.open='1';stopBgm();release();}else{try{$('pauseDlg').close();}catch{}delete $('pauseDlg').dataset.open;last=performance.now();if(!mute)startBgm();}}
bindTap($('sound'),()=>setMute(!mute));
bindTap($('btnPause'),()=>setPaused(true));
bindTap($('btnResume'),()=>setPaused(false));
bindTap($('btnMuteDlg'),()=>setMute(!mute));
bindTap($('btnQuit'),()=>{setPaused(false);state='title';$('title').classList.remove('hidden');$('hud').classList.add('hidden');$('ending').classList.add('hidden');$('battle').classList.add('hidden');$('dialog').classList.add('hidden');stopBgm();});
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function save(){try{localStorage.setItem(saveKey,JSON.stringify(p));}catch{toast('この環境では冒険を保存できません');}}
function refresh(){p.hp=Math.max(0,Math.min(maxHP(),p.hp));p.mp=Math.max(0,Math.min(maxMP(),p.mp));$('level').textContent='Lv. '+p.level;$('hptext').textContent=p.hp+' / '+maxHP();$('mptext').textContent=p.mp+' / '+maxMP();$('hpbar').style.width=p.hp/maxHP()*100+'%';$('mpbar').style.width=p.mp/maxMP()*100+'%';$('gold').textContent=p.gold+' G';$('herbs').textContent='薬草 '+p.herbs;$('crystals').textContent=[0,1,2].map(i=>p.crystals.includes(i)?'◆':'◇').join(' ');$('questtext').textContent=p.won?'島に平和が戻った！':p.crystals.length===3?'北の古城で、灰翼の竜を倒す':'３つの祠で、光のかけらを集める';shrines.forEach(s=>s.gem.visible=!p.crystals.includes(s.i));boss.g.visible=!p.won&&(state!=='battle'||battle?.e===boss);boss.dead=p.won;}
function say(who,text,done){state='dialog';dialogDone=done;$('controls').classList.add('hidden');$('dialog').classList.remove('hidden');$('speaker').textContent=who;$('dialogtext').textContent=text;}
function closeDialog(){if(state!=='dialog')return;$('dialog').classList.add('hidden');state='field';$('controls').classList.remove('hidden');if(dialogDone){let f=dialogDone;dialogDone=null;f();}}
bindTap($('next'),()=>{if(!paused)closeDialog();});
function start(load=false){unlockAudio();if(load){try{const q=JSON.parse(localStorage.getItem(saveKey));if(!q||!Number.isFinite(q.hp)||!Array.isArray(q.crystals)||!Number.isFinite(q.x)||!Number.isFinite(q.z))throw Error();p=q;}catch{toast('保存データを読み込めません');return;}}else{p={x:0,z:15,hp:60,mp:16,level:1,xp:0,gold:0,herbs:4,crystals:[],won:false};enemies.forEach(e=>{e.dead=false;e.cool=0;e.g.visible=true;});}hero.g.position.set(p.x,0,p.z);$('title').classList.add('hidden');$('ending').classList.add('hidden');$('hud').classList.remove('hidden');$('controls').classList.remove('hidden');state='field';refresh();sound([330,440,554,660]);if(!load)say('旅のはじまり','この島の光が、古城の竜に奪われた。\n３つの祠で「光のかけら」を集めよう。\nまずは西の村へ。金色の帽子の村長が、旅を助けてくれる。',save);}
bindTap($('start'),()=>{unlockAudio();start();});bindTap($('continue'),()=>{unlockAudio();start(true);});try{if(localStorage.getItem(saveKey))$('continue').classList.remove('hidden');}catch{}
function useHerb(){if(!p.herbs){toast('薬草がない。村長のところへ戻ろう');return false;}if(p.hp===maxHP()){toast('HPは満タンです');return false;}p.herbs--;p.hp=Math.min(maxHP(),p.hp+35);sound([440,554,660]);refresh();return true;}
bindTap($('heal'),()=>{if(paused)return;if(state==='field'&&useHerb()){toast('薬草でHPを35回復した');save();}});
function interact(){if(state==='dialog'){closeDialog();return;}if(state!=='field')return;if(Math.hypot(p.x+10,p.z-11)<4){p.hp=maxHP();p.mp=maxMP();p.herbs=Math.max(4,p.herbs);refresh();save();sound([392,494,587,784]);say('リーフ村の村長','旅人よ、よく来たね。ゆっくり休んでいきなさい。\nHP・MPを全回復し、薬草を４個まで補充したよ。\n祠は西の森、東の丘、北の道。地図の金色の印を目指すのだ。');return;}for(let s of shrines){if(Math.hypot(p.x-s.x,p.z-s.z)<3.2){if(p.crystals.includes(s.i)){toast('この祠の光は、すでに手に入れた');return;}p.crystals.push(s.i);p.hp=maxHP();p.mp=maxMP();p.gold+=20;refresh();save();sound([523,659,784,1047]);say('光の祠','光のかけらを手に入れた！  '+p.crystals.length+' / 3\n祠の祝福でHP・MPが全回復した。20 G を獲得。'+(p.crystals.length===3?'\n古城の封印が解けた。北の「灰翼の竜」に挑もう。':''));return;}}toast('祠や、村の金色の帽子の人に近づいて調べよう');}
bindTap($('interact'),()=>{if(!paused)interact();});
function beginBattle(e){if(state!=='field'||e.cool>0||e.dead)return;if(e.type===2&&p.crystals.length<3){toast('古城は封印されている。３つの光を集めよう');e.cool=4;return;}state='battle';battle={e,hp:e.type===2?145:e.type===1?44:28,max:e.type===2?145:e.type===1?44:28,turn:0};busy=false;$('battle').classList.remove('hidden');$('controls').classList.add('hidden');$('enemyname').textContent=e.type===2?'灰翼の竜':e.type===1?'ラベンダースライム':'スライム';$('battlelog').textContent=$('enemyname').textContent+' が あらわれた！';enemies.forEach(a=>{a.g.visible=a===e;});hero.g.visible=false;updateBattle();sound([220,277,330]);}
function updateBattle(){refresh();if(!battle)return;$('enemybar').style.width=Math.max(0,battle.hp/battle.max*100)+'%';document.querySelectorAll('[data-command]').forEach(b=>b.disabled=busy||(b.dataset.command==='magic'&&p.mp<4)||(b.dataset.command==='herb'&&(!p.herbs||p.hp===maxHP())));}
function leaveBattle(){let e=battle.e;e.cool=4;battle=null;busy=false;state='field';hero.g.visible=true;enemies.forEach(a=>a.g.visible=!a.dead);$('battle').classList.add('hidden');$('controls').classList.remove('hidden');save();}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function command(c){if(state!=='battle'||busy)return;if(c==='magic'&&p.mp<4)return;if(c==='herb'&&(!p.herbs||p.hp===maxHP()))return;busy=true;let log='',guard=false;const e=battle.e;battle.turn++;
if(c==='run'){if(e.type===2){log='竜の威圧で逃げられない！';}else{leaveBattle();toast('うまく逃げきった！');return;}}
if(c==='attack'||c==='magic'){let damage=c==='magic'?27+p.level*4:10+p.level*4+Math.floor(Math.random()*5);if(c==='magic')p.mp-=4;battle.hp-=damage;log=(c==='magic'?'火の魔法！':'アレンの攻撃！')+' '+damage+' のダメージ！';sound(c==='magic'?[330,660,880]:[180,120]);e.g.rotation.z=.13;setTimeout(()=>e.g.rotation.z=0,180);}
if(c==='herb'){useHerb();log='薬草を使った。HPが35回復した！';}
if(c==='guard'){guard=true;p.mp=Math.min(maxMP(),p.mp+2);log='守りを固めた。MPが2回復した。';}
$('battlelog').textContent=log;updateBattle();await delay(650);
if(battle.hp<=0){e.dead=true;e.g.visible=false;let xp=e.type===2?80:e.type===1?24:16,gold=e.type===2?100:12;p.xp+=xp;p.gold+=gold;let levelup=false;while(p.xp>=p.level*25){p.xp-=p.level*25;p.level++;levelup=true;}if(levelup){p.hp=maxHP();p.mp=maxMP();}sound([523,659,784]);$('battlelog').textContent='勝利！ '+xp+' EXP / '+gold+' G'+(levelup?'\nレベルアップ！ HP・MPが全回復した！':'');refresh();await delay(1050);leaveBattle();if(e.type===2){p.won=true;refresh();save();state='ending';$('controls').classList.add('hidden');$('ending').classList.remove('hidden');$('result').textContent='Lv. '+p.level+'　 /　 '+p.gold+' G　 /　光のかけら 3 / 3';}else{say('戦闘に勝利','魔物を倒した！ '+xp+' EXP と '+gold+' G を手に入れた。'+(levelup?'\nレベル '+p.level+' に上がった！ HP・MPが全回復。':''));}return;}
let breath=e.type===2&&battle.turn%3===0;let damage=Math.max(1,(breath?23:e.type===2?14:e.type===1?10:7)-p.level+Math.floor(Math.random()*3));if(guard)damage=Math.ceil(damage*.3);p.hp-=damage;$('battlelog').textContent=log+'\n'+(breath?'竜の炎の息！':'魔物の攻撃！')+' '+damage+' のダメージ'+(e.type===2&&battle.turn%3===2?'　次は炎が来る！':'');sound([130,95]);refresh();await delay(400);if(p.hp<=0){leaveBattle();p.x=-9;p.z=13;p.hp=maxHP();p.mp=maxMP();p.herbs=Math.max(4,p.herbs);p.gold=Math.floor(p.gold/2);refresh();save();say('リーフ村の村長','気がついたようだね。ここは村だよ。\n持っていたゴールドは半分になったが、光のかけらは無事だ。\n回復と薬草の準備はできている。もう一度、進もう。');}else{busy=false;updateBattle();}}
document.querySelectorAll('[data-command]').forEach(b=>bindTap(b,()=>{if(!paused)command(b.dataset.command);}));
bindTap($('explore'),()=>{state='field';$('ending').classList.add('hidden');$('controls').classList.remove('hidden');});bindTap($('restart'),()=>start());
window.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if($('pauseDlg').open)setPaused(false);else setPaused(true);return;}if(e.code==='KeyP'&&!e.repeat){setPaused(!paused);return;}if(paused)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyQ','KeyR','KeyE'].includes(e.code)){e.preventDefault();key[e.code]=true;if(!e.repeat&&(e.code==='KeyE'||e.code==='Space'))interact();}});window.addEventListener('keyup',e=>key[e.code]=false);function release(){Object.keys(key).forEach(k=>key[k]=false);joy.x=joy.y=0;$('knob').style.transform='';}window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();if(document.hidden){if(state!=='title'&&state!=='ending')setPaused(true);stopBgm();}else last=performance.now();});
let pointer=null;$('stick').addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();pointer=e.pointerId;try{$('stick').setPointerCapture(pointer);}catch{}moveStick(e);});function moveStick(e){if(e.pointerId!==pointer)return;let r=$('stick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,max=r.width/2-8,l=Math.hypot(x,y);if(l>max){x*=max/l;y*=max/l;}joy.x=x/max;joy.y=y/max;$('knob').style.transform=`translate(${x}px,${y}px)`;} $('stick').addEventListener('pointermove',moveStick);for(let name of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(name,()=>{pointer=null;joy.x=joy.y=0;$('knob').style.transform='';});
let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now;},{passive:false});document.addEventListener('touchmove',e=>{if(e.target.closest('[data-scrollable]'))return;e.preventDefault();},{passive:false});document.addEventListener('dblclick',e=>e.preventDefault());document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('selectstart',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault());
function resize(){const wrap=$('screen-wrap');const w=Math.max(1,wrap.clientWidth),h=Math.max(1,wrap.clientHeight);renderer.setSize(w,h,false);const cv=$('world');cv.style.width=w+'px';cv.style.height=h+'px';cv.dataset.logicalWidth=String(w);cv.dataset.logicalHeight=String(h);camera.aspect=w/h;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);resize();
const mapctx=$('map').getContext('2d');function drawMap(){let c=mapctx;c.clearRect(0,0,150,150);c.fillStyle='#7b9c6a';c.beginPath();c.arc(75,75,66,0,Math.PI*2);c.fill();c.strokeStyle='#c7ba85';c.lineWidth=4;c.beginPath();c.moveTo(75,115);c.lineTo(75,30);c.stroke();function dot(x,z,color,r){c.fillStyle=color;c.beginPath();c.arc(75+x*1.8,75+z*1.8,r,0,6.29);c.fill();}shrines.forEach(s=>dot(s.x,s.z,p.crystals.includes(s.i)?'#b6efd6':'#ffe199',4));dot(-13,10,'#fff8d9',4);if(!p.won)dot(0,-23,'#bb6a70',5);dot(p.x,p.z,'#ffffff',4);c.fillStyle='#183d42';c.font='bold 10px serif';c.fillText('N',71,18);}
const target=new T.Vector3(),camPos=new T.Vector3();
function animate(now){requestAnimationFrame(animate);let dt=paused?0:Math.min((now-last)/1000,.04);last=now;if(!paused)time+=dt;shrines.forEach(s=>{s.gem.rotation.y=time;s.gem.position.y=1.7+Math.sin(time*2+s.i)*.13;});enemies.forEach(e=>{e.cool=Math.max(0,e.cool-dt);if(!e.dead){e.g.position.y=Math.sin(time*2+e.id)*.08;if(e.type!==2)e.g.scale.y=1+Math.sin(time*3+e.id)*.035;}});clouds.forEach((c,i)=>c.position.x+=dt*.08);water.position.y=-.8+Math.sin(time)*.035;
if(state==='field'&&!paused){let mx=(key.KeyD||key.ArrowRight?1:0)-(key.KeyA||key.ArrowLeft?1:0)+joy.x,mz=(key.KeyS||key.ArrowDown?1:0)-(key.KeyW||key.ArrowUp?1:0)+joy.y;if(key.KeyQ)yaw+=dt;if(key.KeyR)yaw-=dt;let len=Math.hypot(mx,mz);if(len>.08){mx/=Math.max(1,len);mz/=Math.max(1,len);let dx=(mx*Math.cos(yaw)+mz*Math.sin(yaw))*dt*5.6,dz=(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*dt*5.6;function allowed(x,z){return Math.hypot(x,z)<32.4&&!obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+.35);}if(allowed(p.x+dx,p.z))p.x+=dx;if(allowed(p.x,p.z+dz))p.z+=dz;hero.g.rotation.y=Math.atan2(dx,dz);hero.legs[0].rotation.x=Math.sin(time*12)*.5;hero.legs[1].rotation.x=-Math.sin(time*12)*.5;steps+=dt;if(steps>5){save();steps=0;}}else hero.legs.forEach(l=>l.rotation.x=0);hero.g.position.set(p.x,0,p.z);$('location').textContent=Math.hypot(p.x+14,p.z-10)<9?'リーフ村':p.z<-15?'灰翼の古城':p.x<-13?'風渡りの森':'はじまりの草原';const near=Math.hypot(p.x+10,p.z-11)<4||shrines.some(s=>Math.hypot(p.x-s.x,p.z-s.z)<3.2);$('interact').firstChild.textContent=near?'調べる ':'周囲を見る ';for(let e of enemies){if(!e.dead&&Math.hypot(p.x-e.x,p.z-e.z)<(e.type===2?3:1.7)){beginBattle(e);break;}}}
if(state==='title'){camPos.set(27+Math.sin(time*.06)*3,23,35);target.set(-2,1,0);}else if(state==='battle'&&battle){let e=battle.e;camPos.set(e.x+3.8,e.type===2?4.2:2.8,e.z+(e.type===2?10:7));target.set(e.x,e.type===2?1.7:1,e.z);}else{let distance=($('screen-wrap').clientWidth||innerWidth)<600?21:17;camPos.set(p.x+Math.sin(yaw)*distance,15,p.z+Math.cos(yaw)*distance);target.set(p.x,0,p.z-2);}camera.position.lerp(camPos,Math.min(1,dt*4));camera.lookAt(target);drawMap();renderer.render(scene,camera);}
camera.position.set(27,23,35);requestAnimationFrame(animate);
// Read-only snapshot for diagnostics and automated playthrough evidence.
window.gameSnapshot=()=>({state,player:JSON.parse(JSON.stringify(p)),battle:battle?{hp:battle.hp,type:battle.e.type,turn:battle.turn}:null,position:{x:hero.g.position.x,z:hero.g.position.z},drawCalls:renderer.info.render.calls});
