const { chromium }=require('../../playwright-test/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1365,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8044/244-hajimari-no-shima/');await page.waitForTimeout(1500);await page.screenshot({path:'/tmp/dq3d-title.png'});await page.click('#start');await page.click('#next');await page.keyboard.down('KeyD');await page.waitForFunction(()=>gameSnapshot().player.x>1);await page.keyboard.up('KeyD');assert((await page.evaluate(()=>gameSnapshot())).player.x>1);await page.screenshot({path:'/tmp/dq3d-field.png'});
// Place the player at encounter locations; exercise the actual interaction and combat handlers.
await page.evaluate(()=>{p.x=-10;p.z=11;p.hp=12;p.herbs=0;});await page.click('#interact');assert.equal((await page.evaluate(()=>gameSnapshot())).player.hp,60);await page.click('#next');
for(const [x,z] of [[-21,-7],[18,4],[6,-17]]){await page.evaluate(([x,z])=>{p.x=x;p.z=z;},[x,z]);await page.click('#interact');await page.click('#next');}assert.equal((await page.evaluate(()=>gameSnapshot())).player.crystals.length,3);
await page.evaluate(()=>{p.x=-5;p.z=6;});await page.waitForFunction(()=>gameSnapshot().state==='battle');await page.click('[data-command="magic"]');await page.waitForFunction(()=>gameSnapshot().state==='dialog');await page.click('#next');assert.equal((await page.evaluate(()=>gameSnapshot())).player.mp,12);
await page.evaluate(()=>{p.x=0;p.z=-19;});await page.waitForFunction(()=>gameSnapshot().state==='battle');await page.screenshot({path:'/tmp/dq3d-battle.png'});await page.evaluate(()=>{renderer.setPixelRatio(.5);});
for(let i=0;i<24;i++){let snap=await page.evaluate(()=>gameSnapshot());if(snap.state==='ending')break;assert.equal(snap.state,'battle');const command=snap.player.hp<28&&snap.player.herbs>0?'herb':snap.battle.turn%3===2?'guard':snap.player.mp>=4?'magic':'attack';await page.locator(`[data-command="${command}"]`).click();await page.waitForFunction(()=>state!=='battle'||!busy);}
await page.waitForFunction(()=>gameSnapshot().state==='ending');assert((await page.evaluate(()=>gameSnapshot())).player.won);await page.screenshot({path:'/tmp/dq3d-ending.png'});await page.reload();await page.click('#continue');assert((await page.evaluate(()=>gameSnapshot())).player.won);
await page.evaluate(()=>{p.won=false;p.hp=1;p.x=16;p.z=0;});await page.waitForFunction(()=>gameSnapshot().state==='battle');await page.click('[data-command="guard"]');await page.waitForFunction(()=>gameSnapshot().state==='dialog');let loss=await page.evaluate(()=>gameSnapshot());assert.equal(loss.player.x,-9);assert.equal(loss.player.hp,60+(loss.player.level-1)*16);await page.click('#next');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/dq3d-mobile.png'});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks:['3D rendering','keyboard movement','village recovery','three shrines','spell MP cost','boss victory','ending','save/reload','defeat recovery','mobile layout'],errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
